### ISSUE TITLE
etcd(lector) getsockopt: connection refused 

### ISSUE THREAD

**Issue by sanjid133** [pharmer/pharmer#437]
**How to generate?**

```
cat /etc/kubernetes/kubeadm/config.yaml 
api:
  advertiseAddress: 45.56.93.126
  bindPort: 6443
  controlPlaneEndpoint: ""
apiServerCertSANs:
- 192.168.192.47
- 45.56.93.126
- 96.126.99.15
apiServerExtraArgs:
  kubelet-preferred-address-types: InternalIP,ExternalIP
apiVersion: kubeadm.k8s.io/v1alpha1
auditPolicy:
  logDir: ""
  path: ""
certificatesDir: /etc/kubernetes/pki
cloudProvider: ""
etcd:
  caFile: ""
  certFile: ""
  dataDir: ""
  endpoints: null
  extraArgs:
    advertise-client-urls: https://45.56.93.126:2379
    data-dir: /var/lib/etcd/halim6-master-0
    initial-advertise-peer-urls: https://45.56.93.126:2380
    listen-client-urls: https://45.56.93.126:2379,https://127.0.0.1:2379
    listen-peer-urls: https://45.56.93.126:2380,https://127.0.0.1:2380
    name: halim6-master-0
    quota-backend-bytes: "2147483648"
    server-address: 45.56.93.126
    v: "8"
  image: pharmer/lector:0.1.0-alpha.10
  keyFile: ""
imageRepository: ""
kind: MasterConfiguration
kubeProxy: {}
kubeletConfiguration: {}
kubernetesVersion: v1.10.2
networking:
  dnsDomain: cluster.local
  podSubnet: 192.168.0.0/16
  serviceSubnet: 10.96.0.0/12
nodeName: halim6-master-0
privilegedPods: false
token: ""
tokenTTL: 0s
unifiedControlPlaneImage: ""
```
with this config file run
```
kubeadm init --config /etc/kubernetes/kubeadm/config.yaml
```
After completion check docker ps logs of etcd pod. 

```
time="2018-06-06T04:10:15Z" level=warning msg="failed to create etcd cluster clientLOL" error="dial tcp 45.56.93.126:2379: getsockopt: connection refused"
```

_Running lector(fix branch) directly working with following command_
```
./lector --initial-advertise-peer-urls=https://45.56.93.126:2380 --listen-peer-urls=https://45.56.93.126:2380,https://127.0.0.1:2380 --server-address=45.56.93.126 --data-dir=/var/lib/etcd/halim6-master-0 --listen-client-urls=https://45.56.93.126:2379,https://127.0.0.1:2379 --name=halim6-master-0 --quota-backend-bytes=2147483648 --advertise-client-urls=https://45.56.93.126:2379 --peer-cert-file=/etc/kubernetes/pki/etcd/peer.crt --client-cert-auth=true --peer-client-cert-auth=true --peer-key-file=/etc/kubernetes/pki/etcd/peer.key --peer-trusted-ca-file=/etc/kubernetes/pki/etcd/ca.crt --cert-file=/etc/kubernetes/pki/etcd/server.crt --key-file=/etc/kubernetes/pki/etcd/server.key --trusted-ca-file=/etc/kubernetes/pki/etcd/ca.crt
```
